### ISSUE TITLE
android视频播放器，播放过程中，出现此异常

### ISSUE THREAD

**Issue by caprice** [AgoraIO/Agora-Extensions#1]
2020-03-05 23:25:00.178 7526-7526/io.agora.agoraplayerquickstart E/ActivityThread: Activity io.agora.mediaplayer.MainActivity has leaked IntentReceiver io.agora.rtc2.internal.AudioRoutingController$HeadsetBroadcastReceiver@34df2ef that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity io.agora.mediaplayer.MainActivity has leaked IntentReceiver io.agora.rtc2.internal.AudioRoutingController$HeadsetBroadcastReceiver@34df2ef that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1583)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1316)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1694)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1667)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1655)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at io.agora.rtc2.internal.AudioRoutingController.initialize(AudioRoutingController.java:579)
2020-03-05 23:25:00.214 7526-7526/io.agora.agoraplayerquickstart E/ActivityThread: Activity io.agora.mediaplayer.MainActivity has leaked IntentReceiver io.agora.rtc2.internal.ConnectionChangeBroadcastReceiver@a3b6eda that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity io.agora.mediaplayer.MainActivity has leaked IntentReceiver io.agora.rtc2.internal.ConnectionChangeBroadcastReceiver@a3b6eda that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1583)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1316)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1694)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1667)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1655)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at io.agora.rtc2.internal.CommonUtility.monitorConnectionEvent(CommonUtility.java:197)
        at io.agora.rtc2.internal.CommonUtility.<init>(CommonUtility.java:125)

**Comment by TongJiangyong** [comment]
this log seems shows that has memory leak when exit app, I checked that if you play a video while exit app without call 『stop』 to stop playing video, this error log will appear .we suggest that you should stop the video before exit the activity.
