### ISSUE TITLE
VideoCaptureCamera2 中 getCameraCharacteristics(String id)函数有返回null的情况

### ISSUE THREAD

**Issue by vsloong** [AgoraIO/Agora-Extensions#18]
getCameraCharacteristics(String id)会有部分返回null的情况：
涉及机型：
ReadMi：7、8、K20Pro、Note7 Pro
Honor：7A、Play、HUAWEI Y6 Pro 2019
Vivo：1906、1907

异常信息大致如下，xxx是封装过的其他包名：
Fatal Exception: java.lang.NullPointerException
       at android.os.Parcel.createException(Parcel.java:2093)
       at android.os.Parcel.readException(Parcel.java:2055)
       at android.os.Parcel.readException(Parcel.java:2003)
       at android.hardware.ICameraService$Stub$Proxy.isHiddenPhysicalCamera(ICameraService.java:869)
       at android.hardware.camera2.CameraManager.isHiddenPhysicalCamera(CameraManager.java:911)
       at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:320)
       at xxx..videocapture.video.camera.VideoCaptureCamera2.getCameraCharacteristics(VideoCaptureCamera2.java:227)
       at xxx.videocapture.video.camera.VideoCaptureCamera2.allocate(VideoCaptureCamera2.java:378)
       at cam.honey.videocapture.video.camera.CameraVideoChannel$1.run(CameraVideoChannel.java:72)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       at xxx.videocapture.framework.modules.channels.VideoChannel.run(VideoChannel.java:59)

**Comment by brianxcli** [comment]
请 checkout android_issue_18 这个分支，看看会不会还出现
