### ISSUE TITLE
RuntimeException：set display orientation failed

### ISSUE THREAD

**Issue by NamHofstadter** [AgoraIO/Agora-Extensions#34]
here is the logs
Fatal Exception: java.lang.RuntimeException: set display orientation failed
       at android.hardware.Camera.setDisplayOrientation(Camera.java)
       at io.agora.capture.video.camera.VideoCaptureCamera.allocate(VideoCaptureCamera.java:157)
       at io.agora.capture.video.camera.CameraVideoChannel.lambda$startCapture$0(CameraVideoChannel.java:70)
       at io.agora.capture.video.camera.CameraVideoChannel.lambda$startCapture$0$CameraVideoChannel(CameraVideoChannel.java:4)
       at io.agora.capture.video.camera.-$$Lambda$CameraVideoChannel$jfYgLl6cnwH0Jm775yfLzYtPFNo.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:232)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at io.agora.capture.framework.modules.channels.VideoChannel.run(VideoChannel.java:59)

**Comment by NamHofstadter** [comment]
非必现，非常少但是一直存在，没有特定机型或者Android系统的共通性

**Comment by NamHofstadter** [comment]
@brianxcli 请问有办法解决吗
